name: Pocket B/W
favicon: null
layout_spectrum: 0.24265
typography_spectrum: 0.65137
title: A slice of my world.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b5b0af'
    - '#e4e1e2'
    - '#eeeef0'
    - '#cccbc9'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
